"""Added searchable

Revision ID: 8341a17f9482
Revises: b62a0c2c8edf
Create Date: 2021-11-04 11:02:58.820067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8341a17f9482'
down_revision = 'b62a0c2c8edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'store', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store', type_='unique')
    # ### end Alembic commands ###
