[default]
DEBUG = false
FLASK_ADMIN_SWATCH = 'cerulean'
ADMIN_NAME = 'Entregator'
EXTENSIONS = [
    'entregator.ext.db:init_app',
    'entregator.ext.auth:init_app',
    'entregator.ext.admin:init_app',
    'entregator.ext.migrate:init_app',
    'entregator.ext.cli:init_app',
    'entregator.ext.site:init_app',
    'entregator.ext.hooks:init_app'
]

[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = 'sqlite:///entregator.db'
SQLALCHEMY_TRACK_MODIFICATIONS = false
DEBUG_TB_TEMPLATE_EDITOR_ENABLED = true
DEBUG_TB_PROFILER_ENABLED = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
ADMIN_NAME = 'Entregator (modo dev)'
EXTENSIONS = [
    'entregator.ext.db:init_app',
    'entregator.ext.auth:init_app',
    'entregator.ext.admin:init_app',
    'entregator.ext.migrate:init_app',
    'entregator.ext.cli:init_app',
    'entregator.ext.toolbar:init_app',
    'entregator.ext.site:init_app',
    'entregator.ext.hooks:init_app'
]

[production]
SQLALCHEMY_TRACK_MODIFICATIONS = false  
SQLALCHEMY_DATABASE_URI = 'mysql://...'
